apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - image: zenoffice-front:latest
          name: angular-frontend
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Never
      restartPolicy: Always
