apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
      nodePort: 32000
    - name: "metrics"
      port: 9100
      targetPort: 9100
      nodePort: 32001
  selector:
    app: express-app
