apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9216
      targetPort: 9216
      nodePort: 31001
  selector:
    app: mongodb-exporter
